site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
cmd object = None
cmd object is none tf
before setting assignments
Exception in callback AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22
handle: <Handle AsyncioHelper.on_socket_open.<locals>.cb() at /home/devnico/repos/research/prototype/src/client/proto_asyncio.py:22>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 104, in on_message
    utils._gotCmdToSend.set_result(mapAssignments)
AttributeError: 'NoneType' object has no attribute 'set_result'
in on_message
utils is <proto_utils.ProtoUtils object at 0x779e9058f910>
gotCmdToSend = None
in new subs handler
values = None
execute many = False
^CTraceback (most recent call last):
  File "/home/devnico/repos/research/prototype/src/client/proto_client.py", line 77, in <module>
    main()
  File "/home/devnico/repos/research/prototype/src/client/proto_client.py", line 74, in main
    run_async_client()
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 189, in run_async_client
    loop.run_until_complete(AsyncMqtt(loop).main())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 23, in cb
    client.loop_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/devnico/repos/research/prototype/dev/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/devnico/repos/research/prototype/src/client/proto_asyncio.py", line 98, in on_message
    mapAssignments = algo.generateAssignments()
  File "/home/devnico/repos/research/prototype/src/client/algo_handler.py", line 28, in generateAssignments
    topicsWithNoPublishers = db.topicsWithNoPublishers() # list of tuples with (topic, max_allowed_latency)
  File "/home/devnico/repos/research/prototype/src/client/proto_db.py", line 92, in topicsWithNoPublishers
    return self.execute_query_with_retry(query=selectQuery)
  File "/home/devnico/repos/research/prototype/src/client/proto_db.py", line 34, in execute_query_with_retry
    cursor.execute(query)
KeyboardInterrupt
